### ISSUE TITLE
EE Security Checklist

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/feature-requests#40]
**v4 update**

@mbtamuli please review the following list again as some of it may no longer be relevant to v4.
____

Lets use this issue to add all ideas to secure a server running EE.
- [ ] block unwanted port. EE needs I guess only 22. 80, 443, 3306 and 22222. Rest all can be blocked.
- [ ] Some guide suggsts running SSH on other port. I am against this because port scanning doesn't take much time. Please correct me if I am wrong here.
- [ ] inotify watches for  `~/.ssh/authorized_keys` and other files
- [ ] fail2ban to prevent bruteforce (what about DDoS attach where IP-based filtering fails)?
- [ ] 2-factor authentication for shell users (could be made optional)
