### ISSUE TITLE
v4 Abstract APIs

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/feature-requests#55]
**Update**

Description below is bit outdated. v4 is built using WP CLI as base.
The following checklist reperesent items that v4 needs to provide at some point on its own because there is no equivalent in WP CLI.

____

After going through all options, it looks like most of our work will be around `symfony/console` library. But if we build based on `symfony/console` directly, or use laravel or something else depends on the bigger picture.

Below is list of some components and libraries we will likely need.

*EE_CLI*

- [x] ORM - to interact with SQLite. Laravel - https://laravel.com/docs/5.4/eloquent
- [x] Migration - to manage database changes between upgrades. Laravel - https://laravel.com/docs/5.4/migrations . Outside - https://phinx.org/ looks good. (Moved https://github.com/EasyEngine/easyengine/issues/852)
- [x] Job Queue - to put a long-running process in a job queue. Laravel - https://laravel.com/docs/5.4/queues (moved #1031)
- [x] Cron/Scheduler - a cron manager so at OS level we insert one or few cron and manage other frequents job internally. Laravel - https://laravel.com/docs/5.4/scheduling (moved to https://github.com/EasyEngine/easyengine/issues/1026 )
- [x] Email Service - a wrapper which can queue emails, send them via PHP's sendmail or an external service Amazon SES. Laravel - https://laravel.com/docs/5.4/mail
- [x] Error Logging - Local/remote destination. Level of errors/log message displayed. Laravel - https://laravel.com/docs/5.4/errors
- [ ] Notification Abstraction - Send notifications to Slack or via webhooks. Laravel - https://laravel.com/docs/5.4/notifications
- [x] Docker Wrapper - Looks good https://github.com/docker-php/docker-php (docker-php did not support docker-compose so we built own wrapper https://github.com/EasyEngine/easyengine/blob/master-v4/php/class-ee-docker.php )
- [x] Debian Package Wrapper - _404_ 🕵️(not required EEv4 installs all "packages" as docker image)image)
- [x] Mac Homebrew Wrapper - _404_ 🕵️(not required EEv4 installs all "packages" as docker image)
- [x] Hooks API - a way to inject third-party codes the same way we do it WordPress using action & filter. Seems Laravel has https://laravel.com/docs/5.4/events (Moved to https://github.com/EasyEngine/easyengine/issues/1027)
- [X] Package Manager - Similar to `wp package` command - http://wp-cli.org/commands/package/ (we are using WP_CLI as base so this is sorted)
- [X] Phar distribution - https://github.com/box-project/box2/ looks good (solved in https://github.com/EasyEngine/easyengine/issues/857 and https://github.com/EasyEngine/easyengine/blob/develop-v4/ci/README.md )

*EE_REST_API*

- [ ] Authentication Layer - Laravel - https://laravel.com/docs/5.4/passport
- [ ] Routes and command mapping - Larvel has this built-in https://laravel.com/docs/5.4/artisan#programmatically-executing-commands

*EE_WEB*

Web interface will be made with Laravel for sure! 😉

*Common*

- [x] Test frameworks - PHPUnit, Behat, etc
- [ ] Translation ready. equivalent to i18n/l10n in WordPress ecosystem

### T0-DO

- [x] Finalise - if we will be using Laravel for CLI! Pros vs Cons
- [x] Build independent composer packages e.g. EEStackManager to keep EE core small and share more codes with the community
